<!-- Generated by pkgdown: do not edit by hand -->
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Issue scale data for the ordinal optimal scaling algorithm. — ANES2004_OOC • asmcjr</title>


<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<!-- Bootstrap -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script>

<!-- bootstrap-toc -->
<link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script>

<!-- Font Awesome icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous" />

<!-- clipboard.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>

<!-- headroom.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script>

<!-- pkgdown -->
<link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script>




<meta property="og:title" content="Issue scale data for the ordinal optimal scaling algorithm. — ANES2004_OOC" />
<meta property="og:description" content="Respondent self-identified positions on several issues.  The workspace contains both a data frame including presidential vote and party id (ANES2004_OOC) and one excluding presidential vote and party id ANES2004." />




<!-- mathjax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script>

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->



  </head>

  <body data-spy="scroll" data-target="#toc">
    <div class="container template-reference-topic">
      <header>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">asmcjr</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.0.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/davidaarmstrong/asmcjr/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
      
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

      

      </header>

<div class="row">
  <div class="col-md-9 contents">
    <div class="page-header">
    <h1>Issue scale data for the ordinal optimal scaling algorithm.</h1>
    
    <div class="hidden name"><code>ANES2004_OOC.rd</code></div>
    </div>

    <div class="ref-description">
    <p>Respondent self-identified positions on several issues.  The workspace contains both a data frame including presidential vote and party id (<code>ANES2004_OOC</code>) and one excluding presidential vote and party id <code>ANES2004</code>.</p>
    </div>

    <pre class="usage"><span class='fu'><a href='https://rdrr.io/r/utils/data.html'>data</a></span>(<span class='no'>ANES2004_OOC</span>)</pre>


    <h2 class="hasAnchor" id="format"><a class="anchor" href="#format"></a>Format</h2>

    <p>A data frame with the following variables.</p><dl'>
   <dt>libcon</dt><dd><p>Self-placement on the liberal-conservative scale.</p></dd>
   <dt>diplomacy</dt><dd><p>Placement on intervention by diplomacy/military (1=stronly favor diplomacy, 7=strongly favor military)</p></dd>
   <dt>govtspend</dt><dd><p>Placement on government spending and services (1=government should provide fewer services, 7=government should provide more services)</p></dd>
   <dt>defense</dt><dd><p>Placement on defense spending scale (1=government should decrease defense spending, 7=government should increase defense spending)</p></dd>
   <dt>healthinsurance</dt><dd><p>Placement on government health insurance scale (1=government should provide health insurance, 7=people should buy health insurance from private firms)</p></dd>
   <dt>govtjobs</dt><dd><p>Placement on jobs and standard of living scale (1=government should see to jobs and standard of living, 7=government should let each person get ahead on his or her own)</p></dd>
   <dt>aidblacks</dt><dd><p>Placement on government assistance to blacks scale (1=government should help blacks, 7=blacks should help themselves)</p></dd>
   <dt>govtfundsabortion</dt><dd><p>Favorability toward government funded abortions (1=favor strongly, 4=oppose strongly)</p></dd>
   <dt>partialbirthabortion</dt><dd><p>Favorability toward legality partial birth abortion (1=favor strongly, 4=oppose strongly)</p></dd>
   <dt>environmentjobs</dt><dd><p>Placement on environment vs jobs scale (1=protect environment even if it costs jobs/standard of living, 7=jobs and standard of living are more important than the environment)</p></dd>
   <dt>deathpenalty</dt><dd><p>Favorability toward the death penalty for convicted murderers (1=favor strongly, 4=oppose strongly)</p></dd>
   <dt>gunregulations</dt><dd><p>How much easier should it be to buy a gun (1= a lot harder, 5=a lot easier)</p></dd>
   <dt>womenrole</dt><dd><p>Role of women in society (1=women should have an equal role, 7=a woman's place is in the home)</p></dd>
   <dt>gaymarriage</dt><dd><p>Position on gay marriage (1=allowed, 2=not allowed, but civil union, 3=not allowed at all)</p></dd>
   <dt>presvote</dt><dd><p>Factor indicating whether respondent voted for Bush or Kerry</p></dd>
   <dt>partyid</dt><dd><p>Partisan identification (0=strong democrat, 6=strong republican)</p></dd>

</dl>

    <h2 class="hasAnchor" id="details"><a class="anchor" href="#details"></a>Details</h2>

    <p>See <a href='https://www.electionstudies.org/wp-content/uploads/2018/03/anes_timeseries_2004_vardoc_codebook.txt'>https://www.electionstudies.org/wp-content/uploads/2018/03/anes_timeseries_2004_vardoc_codebook.txt</a> for a full description of all questions.</p>

  </div>
  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">
    <nav id="toc" data-toggle="toc" class="sticky-top">
      <h2 data-toc-skip>Contents</h2>
    </nav>
  </div>
</div>


      <footer>
      <div class="copyright">
  <p>Developed by Dave Armstrong, Royce Carroll, Chris Hare, Ryan Bakker.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.</p>
</div>

      </footer>
   </div>

  


  </body>
</html>


